name: Alt-Tab
favicon: null
layout_spectrum: 0.4061801196075976
typography_spectrum: 0.18115302175283432
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.31004184926860034
  lightness: 0.19354994338937104
  saturation: 0.6881969622336328
  rhythmicContrast: 0.28853825642727315
purpose: []
